export const GET_SINGLE_PRODUCT_START = 'GET_SINGLE_PRODUCT_START';
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';
export const GET_SINGLE_PRODUCT_FAIL = 'GET_SINGLE_PRODUCT_FAIL';
export const GET_SINGLE_PRODUCT_CLEANUP = 'GET_SINGLE_PRODUCT_CLEANUP';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const INCREMENT_PRODUCT_QUANTITY = 'INCREMENT_PRODUCT_QUANTITY';
export const DECREMENT_PRODUCT_QUANTITY = 'GET_SINGLE_PRODUCT_CLEANUP';
export const CART_PRODUCT_CLEANUP = 'CART_PRODUCT_CLEANUP;'
